name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d72219812326aa4bf642890ff2a8ee1e057b5cf7409a569868014d443e0fa8d"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
