name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8274766198e28d0b1827e8be04d5848d4b389c63c332cd5be4673f47e6bce02e"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
