name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b7246a70b613af727ec159475805c5350ffb131903cb274c89f65e9ec4081d2"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
