name = "bv-server"
author = "alikindsys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e3aa4857fcc51d7f2fb60125388fb96727f14b0e6fb7b7d9ddb69c53ba4d1fa"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
