name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a5718cf3abcd7e1ea55d2de691375f49573b6eab50540964e6b115028182e34"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
