name = "bv-server"
author = "alikindsys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "851bab15eae7bd757385f6e483a471718a7b6e9a5c748d03c1d4dc5171272afd"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = []
