name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6391e7f54b6ed8bccaaabcba27aadec65d3f0271a541497d9e57064dd46f81e6"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
