name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44fda94a7c9d24d4fdefe1bab74823885319c4411677d06a3ad199b391b9b880"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
