name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fab391375ecb065f552bb1b9633a6f34e2eceb58357aa26e99ea8a7408cbde1"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0-beta.1"
