name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f64ab961524cc690a424db11983440c00b903f02b9daeaca00d331b15798d43"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
