name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3303e89321d358097ccd35ef855e8ac8f68cee8c6a721e9371ac449f9c2b391"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
