name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b1d11c415b3edd6babcfcb3da0f8db6c1bb00184ad62b3d2563804f6f3705cf"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
