name = "bv-server"
author = "alikindsys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ff081be75a1628349df03d5e5089f0fc850be8f266abf75d98cb1a217bede3a"

[versions]
fabric = "0.19.2"
minecraft = "26.1.1"

[options]
acceptable-game-versions = []
