name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "358093768c81556c99fdfb3924e93f7a8e174e946278f4ef7d120242255a62d6"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
