name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a8430b9fd2af5a8f0ad18b29d164b97b4b0af4f0e4185b644d13e4b5b023320"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0-beta.1"
