name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "688508bb5c5b2942ff0b6d5aeaa71bd451eaf25c9d950e5a8074e881b7ed71cf"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
